/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { ConcordiaApiContext } from "./concordiaApiContext";

class ConcordiaApi extends ConcordiaApiContext {
  // Operation groups
  apiTokenAuth: operations.ApiTokenAuth;
  apiTokenRefresh: operations.ApiTokenRefresh;
  api: operations.Api;
  departament: operations.DepartamentOperations;
  document: operations.Document;
  person: operations.PersonOperations;
  procedure: operations.ProcedureOperations;
  register: operations.Register;
  user: operations.UserOperations;

  /**
   * Initializes a new instance of the ConcordiaApi class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.ConcordiaApiOptions) {
    super(options);
    this.apiTokenAuth = new operations.ApiTokenAuth(this);
    this.apiTokenRefresh = new operations.ApiTokenRefresh(this);
    this.api = new operations.Api(this);
    this.departament = new operations.DepartamentOperations(this);
    this.document = new operations.Document(this);
    this.person = new operations.PersonOperations(this);
    this.procedure = new operations.ProcedureOperations(this);
    this.register = new operations.Register(this);
    this.user = new operations.UserOperations(this);
  }
}

// Operation Specifications

export {
  ConcordiaApi,
  ConcordiaApiContext,
  Models as ConcordiaApiModels,
  Mappers as ConcordiaApiMappers
};
export * from "./operations";
